### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by celyes** [softvenue/learn-git#4]
@Aissaoui-Ahmed
الموقع لا يعمل 
الرجاء القيام بإعادة الرأس إلى:  
`39c3b41`
باستعمال
`git reset --hard 39c3b41`

**Comment by Aissaoui-Ahmed** [comment]
<div dir="rtl" >المشكل في الملف CNAME </div>
<div dir="rtl" >لايتم إنشاء الملف من طرف travis </div>
<div dir="rtl" >  سأعمل على الحل شكرا @celyes  </div>
